### ISSUE TITLE
Add style to the home page

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/python-sprints.github.io#1]
The home page of the Python sprints in incomplete and lacking any styles: https://python-sprints.github.io/

We could have a nicer website by using a template [1], and also adding more sections:
* Explanation of what is the group about
* Section for future and past sprints
* Sponsors section, with logos and links of our main sponsors
* Useful links section
* Anything else that can be useful.

1. https://startbootstrap.com/template-categories/all/

**Comment by Tomasz-Kluczkowski** [comment]
Hi Marc,

I have noticed several issues with the looks of the new version of the home page on mobiles (this was only partially tested on small screens :) due to time hehe). 
Already fixed locally a few but the layout breaks at the top due to large fonts and image is not positioned correctly (the running man is partially cut).

I will fix those and create a new pull request.

In the meantime I am going to learn this jekyll thingy, might be useful in the future.

If you have time I need to know what do we want to have in the site's navigation.
So far I just put About / Projects / Getting Started / Contact - let me know if you want to add / remove / subdivide those.

For example the Getting started can be divided into all the tutorials that we need to prepare for the newcomers so it could have a submenu (it should fit as we have a full screen navigation).
Like: Getting Started
          |___ First Pull Request
          |___ Contributing to Pandas

etc....

C u,

Tomasz

**Comment by datapythonista** [comment]
I'll give you permissions on the repo, so you can do the changes directly.

For the sections, the ones you mentioned sound good, but I think one
linking to the sprint descriptions would be useful too. This is were jekyll
can be useful, as this section could be automatically updated as we add new
events.

**Comment by Tomasz-Kluczkowski** [comment]
So i think we should create a section Upcoming Event in the top, right under Our Mission with some way of sticking content there easy through jekyll?

Also I am thinking of moving the sponsors out of the footer (they take too much space when layout collapses on mobiles) and creating a separate section just before the footer called Our Sponsors where I would be able to put their logos a bit bigger and 2 -3 lines of text about what they do, maybe mention the person who is helping if they want to be mentioned..

**Comment by datapythonista** [comment]
Sounds great.

I don't think it's trivial to separate the upcoming events from the past
events in Jekyll. May be that can be better done with JavaScript. But
getting the last 3 or 4 events with Jekyll should be easy (once we know how
Jekyll works).

Btw, did you receive the invitation for the python-sprints GitHub
organisation?

**Comment by Tomasz-Kluczkowski** [comment]
I did get it and joined - thx.
I will work on this project a few times a week.
Initially I will fix all the home page bugs for smaller screens.

Ok so I shall find a way to feed last few events somehow.
Correct me if I am wrong - jekyll still needs us to put some template file and add content manually(though it will be easy as the template makes it look nice). I cannot make jekyll pull data from our Meetup page right? Still some manual copy/pasting of the meetup info is required?



On 9 Feb 2018, at 12:55, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds great.

I don't think it's trivial to separate the upcoming events from the past
events in Jekyll. May be that can be better done with JavaScript. But
getting the last 3 or 4 events with Jekyll should be easy (once we know how
Jekyll works).

Btw, did you receive the invitation for the python-sprints GitHub
organisation?

**Comment by Tomasz-Kluczkowski** [comment]
One more question - this time on the correct way of making changes to the repo.

Should I continue working on my fork, making pull requests which then I can myself accept (since I received write permission s) from the the actual python-sprints repo or rather clone the real thing and push directly to it?

I think it is still better to create pull requests for transparency but you advice is welcome.

Have a great weekend :).

On 9 Feb 2018, at 12:55, Marc Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds great.

I don't think it's trivial to separate the upcoming events from the past
events in Jekyll. May be that can be better done with JavaScript. But
getting the last 3 or 4 events with Jekyll should be easy (once we know how
Jekyll works).

Btw, did you receive the invitation for the python-sprints GitHub
organisation?

**Comment by datapythonista** [comment]
Regarding jekyll pulling from meetup... The jekyll build script will be run every time we push to this repo, and never afterwards. This means that if we create a new event in meetup, it wouldn't be added to the website even if jekyll could access meetup data (which I don't think it can).

So, the idea with jekyll is that instead of having to create a new page with all the format for every event, we could simply add a rst file with the info, and all the format would be inherited from a jekyll template.

Also, we could have predefined blocks, for example the info about the sponsors in a file harvey_nash.rst, and when creating the event we could just import that block, and we don't need to copy that content "manually".

So, no integration would exist with meetup, but now to create a page like:
https://python-sprints.github.io/2018/february/python-sprints-website.html

we upload an independent html file. With jekyll, we would push to the repo a file sprint_pandas_2018_march.rst, and all the formatting, and the reusable blocks (sponsor, environment set up, project description...) will be managed by jekyll to end up with a static html that will be published.

About sending pull requests or not... If you want to push directly, you don't need to clone, simply:
`git remote set-url origin git@github.com:python-sprints/python-sprints.github.io.git`

and then you can pull and push from the original repo like if you cloned from it.

If you keep the remotes as they are, you can do a `git push upstream` to push directly without opening a pull request. And `git push` to do it with a pull request. Feel free to use the option you like the most.

**Comment by Tomasz-Kluczkowski** [comment]
I have created a new branch fix_title.
All the issues with incorrect layouts at different screen sizes including checking of portrait / landscape modes on multiple devices (in google dev tool) done.
Added more title images to provide correct sizes for high pixel density screens.
Fixed text overflowing in all sections (titles).

Shall I just merge this to master ?

**Comment by datapythonista** [comment]
Yes please. Thanks!

**Comment by Tomasz-Kluczkowski** [comment]
Hey,

Home page is in its infant but more or less full content version now.
I added automatically generated upcoming event (unfinished styling, need to add links and sponsor logos over the background image and fix responsive design - it breaks on mobiles). 
This section will show only the closest upcoming event to the current date.
We can change that if needed and show all upcoming events... but I think it would then pollute the site with too much info :).

Is Bloomberg the only sponsor for our London Pandas Sprint as I added that only ATM? Can I have the full list of sponsors (and do we want all of them for worldwide or only the London ones) so I can add their logos?

Please let me know if you want more sections on home page and what would they be.

After I finish styling the upcoming event I will work on the subpages from the navigation menu (at least their initial version).

**Comment by Tomasz-Kluczkowski** [comment]
Closed as enough info obtained.
